services:
  - type: web
    name: arush-vc-bot
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: bash start
    autoDeploy: true
    envVars:
      - key: API_ID
        value: "29448785"
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: OWNER_ID
        value: "7574330905"
      - key: OWNER_USERNAME
        value: WTF_WhyMeeh
      - key: BOT_USERNAME
        value: ARUSHxVC-BOT
      - key: UPSTREAM_REPO
        value: https://github.com/opanshuff2k/arush-vc-bot
      - key: STRING_SESSION
        sync: false
      - key: GIT_TOKEN
        sync: false
      - key: HEROKU_API_KEY
        sync: false
      - key: HEROKU_APP_NAME
        sync: false
      - key: LOG_GROUP_ID
        value: "-1002321189618"
      - key: SUPPORT_GROUP
        value: https://t.me/ARUSHxVCBOTupport
      - key: SUPPORT_CHANNEL
        value: https://t.me/ARUSHxVCBOT
      - key: INSTAGRAM
        value: https://instagram.com/yaduwanshi_nand
      - key: YOUTUBE
        value: https://youtube.com/@NandEditz
      - key: GITHUB
        value: https://github.com/opanshuff2k
      - key: DONATE
        value: https://t.me/ARUSHxVCBOT/91
      - key: START_IMG_URL
        sync: false
