services:
  - type: web
    name: arush-vc-bot
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m ARUSHxVCBOT
    autoDeploy: true

    envVars:
      API_ID: 
        value: 29448785
      API_HASH: 
        sync: false
      API_KEY:
        sync: false
      BOT_TOKEN:
        sync: false
      MONGO_DB_URI: 
        sync: false
      OWNER_ID:
        value: 7574330905
      OWNER_USERNAME:
        value: WTF_WhyMeeh
      BOT_USERNAME:
        value: ARUSHxVC-BOT
      UPSTREAM_REPO:
        value: https://github.com/opanshuff2k/arush-vc-bot
      STRING_SESSION:
        sync: false
      GIT_TOKEN:
        sync: false
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      LOG_GROUP_ID:
        value: -1002321189618
      SUPPORT_GROUP:
        value: https://t.me/ARUSHxVCBOTupport
      SUPPORT_CHANNEL:
        value: https://t.me/ARUSHxVCBOT
      INSTAGRAM:
        value: https://instagram.com/yaduwanshi_nand
      YOUTUBE:
        value: https://youtube.com/@NandEditz
      GITHUB:
        value: https://github.com/opanshuff2k
      DONATE:
        value: https://t.me/ARUSHxVCBOT/91
      START_IMG_URL:
        sync: false
